# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "errcheck-unstable-${version}";
  version = "2018-08-07";
  # Version with go module support. See https://github.com/kisielk/errcheck/issues/150.
  rev = "355fb1c0ffd69d82ee81377edb8bbeb738c11819";

  goPackagePath = "github.com/kisielk/errcheck";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/kisielk/errcheck";
    sha256 = "1fsm8hp0xk2q80jval6aqsfx1shscpb07885lzwyg7mmd8hfq3pc";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
