# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "errcheck-unstable-${version}";
  version = "2018-08-07";
  rev = "1787c4bee836470bf45018cfbc783650db3c6501";

  goPackagePath = "github.com/kisielk/errcheck";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/kisielk/errcheck";
    sha256 = "0070150hmhdk9q6n78il0m6a2g8l4r0b9m2jsiq2c7sh7imzcdbb";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
