# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/kisielk/gotool";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/gotool";
      rev = "d6ce6262d87e3a4e153e86023ff56ae771554a41";
      sha256 = "1gq26rx7rhwhfj2ql079xnj94k4gqsg9n0s2ccp86mcg1rsd9zyc";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "e4b401d06e5ee9f990011dc4f24cd24162131565";
      sha256 = "1f0krr2cm2n6kisrcjq2989cj1s82qrbmmdz89mpv4mzgd57lah1";
    };
  }
]
