# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "3c07937fe18c27668fd78bbaed3d6b8b39e202ea";
      sha256 = "0hvrp8dpg9p15s45p4fhv7hjgdvazjh9vw4mm4j6ha9zqc56qdba";
    };
  }
]
