# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/kisielk/gotool";
    fetch = {
      type = "git";
      url = "https://github.com/kisielk/gotool";
      rev = "80517062f582ea3340cd4baf70e86d539ae7d84d";
      sha256 = "14af2pa0ssyp8bp2mvdw184s5wcysk6akil3wzxmr05wwy951iwn";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "73e16cff9e0d4a802937444bebb562458548241d";
      sha256 = "1qjjh6nfgpz97zga62m7vj6kcf830yiksxbyb9slyvkwfll5f9p3";
    };
  }
]
