#!/bin/sh

set -e

BASE_URL=https://raw.githubusercontent.com/github/gitignore/master/
IGNORES='Global/Emacs.gitignore Global/OSX.gitignore Global/vim.gitignore'

cat ignore.local > ignore

for s in ${IGNORES}; do
  curl -s "${BASE_URL}/${s}" >> ignore
done
